apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
  labels:
   app: my-app-2
spec:
  containers:
  - name: my-container
    image: iamrajagovindaraj/nginx-test:1.0
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html # Mount point within the container
      name: my-volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc
