apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-cloned-pvc
spec:
  storageClassName: standard
  dataSource:
    name: my-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 1Gi
