apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: test-namespace
spec:
  storageClassName: standard  # Reference the StorageClass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: my-pv  # Reference the PersistentVolume by name
