apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: standard  # Reference the StorageClass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
