apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app  # Selects pods with this label
  ports:
    - protocol: TCP
      port: 80      # Port the service exposes internally
      targetPort: 80 # Port the application listens on within the pod
      nodePort: 30001  # Optional: Specify a NodePort (30000-32767) or let Kubernetes assign one
  type: NodePort
